ignored = [
    "github.com/mholt/caddy",
    "github.com/mholt/caddy/caddyfile",
    "github.com/mholt/caddy/caddyhttp",
    "github.com/mholt/caddy/startupshutdown",
    "github.com/mholt/caddy/onevent",
    "github.com/mholt/caddy/caddyhttp/httpserver",
]

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/mholt/caddy"
  version = "0.10.14"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
